type: CCard
header: 7
where: e
date: a
payee: |
    [c, g, d].join(' ')
category: m
amount: -f.to_f
num: l
address: |
    j ? k ? j+"\n"+k : j : k
mappings:
    - /-/:/
    - /^/Private:Expenses:2009:/