type: CCard
header: 0
date_format: |
    %m/%d/%Y
encoding: ISO-8859-1    
where: e
date: a
payee: |
    [c, j].join(' ')
category: |
    "Private:Expenses:2013"
amount: -h.to_f
num: o
address: |
    [l,m,n].compact.join "\n"
